using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    /// <inheritdoc />
    public partial class AddSkillsTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT FROM pg_tables 
                        WHERE schemaname = 'public' 
                        AND tablename = 'Skills'
                    ) THEN
                        CREATE TABLE ""Skills"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""Name"" character varying(100) NOT NULL,
                            ""Description"" character varying(500),
                            ""Category"" character varying(100) NOT NULL,
                            ""Level"" character varying(20),
                            ""CreatedUser"" character varying(100) NOT NULL,
                            ""ModifyUser"" character varying(100),
                            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                            ""UpdatedAt"" timestamp with time zone,
                            ""IsActive"" boolean NOT NULL DEFAULT true,
                            ""IsDeleted"" boolean NOT NULL DEFAULT false
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT FROM pg_tables 
                        WHERE schemaname = 'public' 
                        AND tablename = 'UserSkills'
                    ) THEN
                        CREATE TABLE ""UserSkills"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""UserId"" integer NOT NULL,
                            ""SkillId"" integer NOT NULL,
                            ""ProficiencyLevel"" character varying(20),
                            ""YearsOfExperience"" integer,
                            ""Certifications"" character varying(500),
                            ""Notes"" character varying(1000),
                            ""AssignedBy"" character varying(100) NOT NULL,
                            ""AssignedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                            ""IsActive"" boolean NOT NULL DEFAULT true,
                            CONSTRAINT ""FK_UserSkills_Skills_SkillId"" 
                                FOREIGN KEY (""SkillId"") 
                                REFERENCES ""Skills""(""Id"") 
                                ON DELETE CASCADE,
                            CONSTRAINT ""FK_UserSkills_Users_UserId"" 
                                FOREIGN KEY (""UserId"") 
                                REFERENCES ""Users""(""Id"") 
                                ON DELETE CASCADE
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_Skills_Name'
                    ) THEN
                        CREATE UNIQUE INDEX ""IX_Skills_Name"" ON ""Skills"" (""Name"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_Skills_Category'
                    ) THEN
                        CREATE INDEX ""IX_Skills_Category"" ON ""Skills"" (""Category"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_UserSkills_SkillId'
                    ) THEN
                        CREATE INDEX ""IX_UserSkills_SkillId"" ON ""UserSkills"" (""SkillId"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_UserSkills_UserId_SkillId'
                    ) THEN
                        CREATE INDEX ""IX_UserSkills_UserId_SkillId"" ON ""UserSkills"" (""UserId"", ""SkillId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTableIfExists("UserSkills");
            migrationBuilder.DropTableIfExists("Skills");
        }
    }
}
