using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    /// <inheritdoc />
    public partial class AddRolesTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Roles') THEN
                        CREATE TABLE ""Roles"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""Name"" character varying(100) NOT NULL,
                            ""Description"" character varying(500),
                            ""CreatedUser"" character varying(100) NOT NULL,
                            ""ModifyUser"" character varying(100),
                            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                            ""UpdatedAt"" timestamp with time zone,
                            ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                            ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
                            CONSTRAINT ""PK_Roles"" PRIMARY KEY (""Id"")
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'UserRoles') THEN
                        CREATE TABLE ""UserRoles"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""UserId"" integer NOT NULL,
                            ""RoleId"" integer NOT NULL,
                            ""AssignedBy"" character varying(100) NOT NULL,
                            ""AssignedAt"" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                            ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                            CONSTRAINT ""PK_UserRoles"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_UserRoles_MainAdminUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""MainAdminUsers"" (""Id"") ON DELETE CASCADE,
                            CONSTRAINT ""FK_UserRoles_Roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE CASCADE
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'Roles' AND indexname = 'IX_Roles_Name') THEN
                        CREATE UNIQUE INDEX ""IX_Roles_Name"" ON ""Roles"" (""Name"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'UserRoles' AND indexname = 'IX_UserRoles_RoleId') THEN
                        CREATE INDEX ""IX_UserRoles_RoleId"" ON ""UserRoles"" (""RoleId"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'UserRoles' AND indexname = 'IX_UserRoles_UserId_RoleId') THEN
                        CREATE INDEX ""IX_UserRoles_UserId_RoleId"" ON ""UserRoles"" (""UserId"", ""RoleId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserRoles");

            migrationBuilder.DropTable(
                name: "Roles");
        }
    }
}
