using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    /// <inheritdoc />
    public partial class CreateUsersTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT FROM pg_tables 
                        WHERE schemaname = 'public' 
                        AND tablename = 'Users'
                    ) THEN
                        CREATE TABLE ""Users"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""Email"" character varying(255) NOT NULL,
                            ""PasswordHash"" character varying(255) NOT NULL,
                            ""FirstName"" character varying(100) NOT NULL,
                            ""LastName"" character varying(100) NOT NULL,
                            ""PhoneNumber"" character varying(20),
                            ""Country"" character varying(2) NOT NULL,
                            ""CreatedUser"" character varying(100) NOT NULL,
                            ""ModifyUser"" character varying(100),
                            ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            ""ModifyDate"" timestamp with time zone,
                            ""IsActive"" boolean NOT NULL DEFAULT true,
                            ""IsDeleted"" boolean NOT NULL DEFAULT false,
                            ""Role"" character varying(50),
                            ""LastLoginAt"" timestamp with time zone,
                            ""AccessToken"" character varying(500),
                            ""RefreshToken"" character varying(500),
                            ""TokenExpiresAt"" timestamp with time zone
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_Users_Email'
                    ) THEN
                        CREATE UNIQUE INDEX ""IX_Users_Email"" ON ""Users"" (""Email"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTableIfExists("Users");
        }
    }
}
