using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreatePostgreSQL : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT FROM pg_tables 
                        WHERE schemaname = 'public' 
                        AND tablename = 'MainAdminUsers'
                    ) THEN
                        CREATE TABLE ""MainAdminUsers"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""Email"" character varying(255) NOT NULL,
                            ""PasswordHash"" character varying(255) NOT NULL,
                            ""FirstName"" character varying(100) NOT NULL,
                            ""LastName"" character varying(100) NOT NULL,
                            ""PhoneNumber"" character varying(20),
                            ""Country"" character varying(2) NOT NULL,
                            ""Industry"" character varying(100) NOT NULL,
                            ""AccessToken"" character varying(500),
                            ""RefreshToken"" character varying(500),
                            ""TokenExpiresAt"" timestamp with time zone,
                            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                            ""UpdatedAt"" timestamp with time zone,
                            ""IsActive"" boolean NOT NULL DEFAULT true,
                            ""LastLoginAt"" timestamp with time zone,
                            ""CompanyName"" character varying(255),
                            ""CompanyWebsite"" character varying(500),
                            ""Preferences"" text
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT FROM pg_tables 
                        WHERE schemaname = 'public' 
                        AND tablename = 'UserPreferences'
                    ) THEN
                        CREATE TABLE ""UserPreferences"" (
                            ""Id"" text PRIMARY KEY,
                            ""UserId"" integer NOT NULL,
                            ""Theme"" character varying(20) NOT NULL DEFAULT 'system',
                            ""Language"" character varying(5) NOT NULL DEFAULT 'en',
                            ""PrimaryColor"" character varying(20) NOT NULL DEFAULT 'blue',
                            ""LayoutMode"" character varying(20) NOT NULL DEFAULT 'sidebar',
                            ""DataView"" character varying(10) NOT NULL DEFAULT 'table',
                            ""Timezone"" character varying(100),
                            ""DateFormat"" character varying(20) NOT NULL DEFAULT 'MM/DD/YYYY',
                            ""TimeFormat"" character varying(5) NOT NULL DEFAULT '12h',
                            ""Currency"" character varying(5) NOT NULL DEFAULT 'USD',
                            ""NumberFormat"" character varying(10) NOT NULL DEFAULT 'comma',
                            ""Notifications"" text DEFAULT '{}',
                            ""SidebarCollapsed"" boolean NOT NULL DEFAULT false,
                            ""CompactMode"" boolean NOT NULL DEFAULT false,
                            ""ShowTooltips"" boolean NOT NULL DEFAULT true,
                            ""AnimationsEnabled"" boolean NOT NULL DEFAULT true,
                            ""SoundEnabled"" boolean NOT NULL DEFAULT true,
                            ""AutoSave"" boolean NOT NULL DEFAULT true,
                            ""WorkArea"" character varying(100),
                            ""DashboardLayout"" text,
                            ""QuickAccessItems"" text DEFAULT '[]',
                            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                            ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                            CONSTRAINT ""FK_UserPreferences_MainAdminUsers_UserId"" 
                                FOREIGN KEY (""UserId"") 
                                REFERENCES ""MainAdminUsers""(""Id"") 
                                ON DELETE CASCADE
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_MainAdminUsers_Email'
                    ) THEN
                        CREATE UNIQUE INDEX ""IX_MainAdminUsers_Email"" ON ""MainAdminUsers"" (""Email"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_MainAdminUsers_CreatedAt'
                    ) THEN
                        CREATE INDEX ""IX_MainAdminUsers_CreatedAt"" ON ""MainAdminUsers"" (""CreatedAt"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_MainAdminUsers_IsActive'
                    ) THEN
                        CREATE INDEX ""IX_MainAdminUsers_IsActive"" ON ""MainAdminUsers"" (""IsActive"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND indexname = 'IX_UserPreferences_UserId'
                    ) THEN
                        CREATE UNIQUE INDEX ""IX_UserPreferences_UserId"" ON ""UserPreferences"" (""UserId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTableIfExists("UserPreferences");
            migrationBuilder.DropTableIfExists("MainAdminUsers");
        }
    }
}
